### ISSUE TITLE
example code "use" statement

### ISSUE THREAD

**Issue by kylerlaird** [DogeDark/dioxus-logger#2]
I'm new to Rust.  I appreciate dioxus-logger and I'm looking forward to its further development.

The example code includes "use log::{LevelFilter, info};".  This results in an error when I use it.  The error is eliminated by using "use dioxus_logger;" instead.  Am I doing something wrong?

**Comment by DogeDark** [comment]
Hey! Sorry for the late response. I haven't had the time to work on dioxus logger and just saw this. The example uses older versions of dioxus and log. I have provided a working example for the web target below. 

```rs
use dioxus::prelude::*;
use log::{info, LevelFilter};

fn main() {
    dioxus_logger::init(LevelFilter::Info).expect("failed to init logger");
    dioxus_web::launch(app);
}

fn app(cx: Scope) -> Element {
    info!("my app component just rendered!");
    cx.render(rsx!(p { "Hello, Dioxus!" }))
}
```

Your cargo.toml should have these dependencies:
```toml
dioxus-logger = { version = "0.3", features = ["timestamps"] }
dioxus = "0.3.2"
dioxus-web = "0.3.1"
log = "0.4.17"
```

Let me know if this works and welcome to Rust & Dioxus!
